[package]
name = "basic_allocator"
version = "0.1.1"
description = "A very simple global allocator written in pure Rust"
repository = "https://github.com/wackywendell/basicalloc"
license-file = "LICENSE"
readme = "README.md"
authors = ["Wendell Smith <wackywendell@gmail.com>"]
edition = "2018"

[dependencies]
# libc is used to get pages of virtual memory from the Unix OS
libc = "0.2"
# sysconf tells us the size of a page
sysconf = "0.3"
# log is used for logging. This mostly doesn't work inside the allocator because
# of recursion, but can be useful in tests.
log = "0.4"
# Static assertions check that our assumptions are valid at compile-time
static_assertions = "1.1"
# A spin lock is used to protect the allocator in a multi-threaded capacity.
spin = "0.5"

[dev-dependencies]
env_logger = "0.7"
test-env-log = "0.2"
rand = "0.7"