[package]
name = "basicalloc"
version = "0.1.0"
authors = ["Wendell Smith <wackywendell@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2"
log = "0.4"
static_assertions = "1.1"
spin = "0.5"

[dev-dependencies]
# pretty_env_logger = "0.3"
env_logger = "*"
test-env-log = "0.2"