[package]
name = "basic_allocator"
version = "0.1.0"
description = "A very simple global allocator written in pure Rust"
repository = "https://github.com/wackywendell/basicalloc"
license-file = "LICENSE"
readme = "README.md"
authors = ["Wendell Smith <wackywendell@gmail.com>"]
edition = "2018"

[dependencies]
libc = "0.2"
sysconf = "0.3"
log = "0.4"
static_assertions = "1.1"
spin = "0.5"

[dev-dependencies]
env_logger = "0.7"
test-env-log = "0.2"
rand = "0.7"